### PR TITLE
Issue 226

### LINKED ISSUE #226: 'ffmpeg_avcodec_log: Application provided invalid, non monotonically increasing dts to muxer in stream'
Hi,
I have an issue with ffmpeg/libav library (I guess). 

This is my setup:
```
$ uname -a
Linux localhost.localdomain 4.3.0-rc1-225164-g7c2251d-dirty #12 SMP Tue Sep 20 13:22:36 CEST 2016 armv7l armv7l armv7l GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
```

Pre-installation steps:
```
$ git clone https://github.com/Motion-Project/motion.git
$ cd motion
$ apt-get install autoconf automake libtool libjpeg8-dev build-essential libzip-dev pkgconf
$ apt-get install libavformat-dev libavcodec-dev libavutil-dev libav-tools libswscale-dev
```

Installation steps:
```
$ autoreconf -fiv
$ ./configure
$ make
$ make install
```

The issue: 'Application provided invalid, non monotonically increasing dts to muxer in stream 0: 2 >= 2'

This is the log issue:
```
[0] [NTC] [ALL] conf_load: Processing thread 0 - config file /usr/local/etc/motion/motion.conf
[0] [NTC] [ALL] motion_startup: Motion 3.4.1+git599af71 Started
[0] [NTC] [ALL] motion_startup: Logging to syslog
[0] [NTC] [ALL] motion_startup: Using log type (ALL) log level (NTC)
[0] [NTC] [ENC] ffmpeg_init: ffmpeg libavcodec version 54.35.0 libavformat version 54.20.3
[0] [NTC] [ALL] main: Camera 0 is from /usr/local/etc/motion/motion.conf
[0] [NTC] [ALL] main: Camera 0 is device: /dev/video2 input -1
[0] [NTC] [ALL] main: Stream port 8081
[0] [NTC] [ALL] main: Waiting for threads to finish, pid: 3582
[0] [NTC] [STR] http_bindsock: listening on any address port 8080
[0] [NTC] [STR] httpd_run: Started motion-httpd server on port 8080 (auth Disabled)
[1] [NTC] [ALL] motion_init: Camera 0 started: motion detection Enabled
[1] [NTC] [VID] vid_v4lx_start: Using videodevice /dev/video2 and input -1
[1] [NTC] [VID] v4l2_get_capability: 
------------------------
cap.driver: "ispvideo"
cap.card: "OMAP3 ISP CCDC output"
cap.bus_info: "media"
cap.capabilities=0x84200003
------------------------
[1] [NTC] [VID] v4l2_get_capability: - VIDEO_CAPTURE
[1] [NTC] [VID] v4l2_get_capability: - VIDEO_OUTPUT
[1] [NTC] [VID] v4l2_get_capability: - STREAMING
[1] [NTC] [VID] v4l2_select_input: name = "camera", type 0x00000002, status 00000000
[1] [NTC] [VID] v4l2_select_input: - CAMERA
[1] [WRN] [VID] v4l2_select_input: Device doesn't support VIDIOC_G_STD
[1] [NTC] [VID] v4l2_do_set_pix_format: Testing palette Y12  (320x240)
[1] [WRN] [VID] v4l2_do_set_pix_format: Adjusting resolution from 320x240 to 1024x768.
[1] [NTC] [VID] v4l2_do_set_pix_format: Using palette Y12  (1024x768) bytesperlines 2048 sizeimage 1572864 colorspace 00000008
[1] [NTC] [VID] vid_v4lx_start: Using V4L2
[1] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 1 items
[1] [NTC] [STR] http_bindsock: listening on any address port 8081
[1] [NTC] [ALL] motion_init: Started motion-stream server on port 8081 (auth Disabled)
[1] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 3 items
[1] [NTC] [EVT] event_new_video Source FPS 3
[1] [NTC] [ENC] ffmpeg_open Selected Output FPS 3
[1] [NTC] [EVT] event_newfile: File of type 8 saved to: /root/.motion/output/01-20161006164334.avi
[1] [NTC] [ALL] motion_detected: Motion detected - starting event 1

{..}

[1] [NTC] [EVT] event_newfile: File of type 1 saved to: /root/.motion/output/01-20161006164432-00.jpg
[1] [NTC] [EVT] event_newfile: File of type 1 saved to: /root/.motion/output/01-20161006164432-01.jpg
[1] [NTC] [EVT] event_newfile: File of type 1 saved to: /root/.motion/output/01-20161006164433-00.jpg
[1] [NTC] [EVT] event_newfile: File of type 1 saved to: /root/.motion/output/01-20161006164433-01.jpg
[1] [NTC] [ALL] motion_loop: End of event 1
[1] [NTC] [EVT] event_newfile: File of type 1 saved to: /root/.motion/output/02-20161006164434-00.jpg
[1] [NTC] [EVT] event_new_video Source FPS 2
[1] [NTC] [ENC] ffmpeg_open Selected Output FPS 2
[1] [NTC] [EVT] event_newfile: File of type 8 saved to: /root/.motion/output/02-20161006164434.avi
[1] [NTC] [ALL] motion_detected: Motion detected - starting event 2
[1] [NTC] [EVT] event_newfile: File of type 1 saved to: /root/.motion/output/02-20161006164434-01.jpg
[1] [NTC] [EVT] event_newfile: File of type 1 saved to: /root/.motion/output/02-20161006164435-00.jpg
[1] [ERR] [ENC] ffmpeg_avcodec_log: Application provided invalid, non monotonically increasing dts to muxer in stream 0: 2 >= 2
[1] [ERR] [ENC] ffmpeg_put_frame: Error while writing video frame: No such file or directory
[1] [NTC] [ALL] motion_loop: Thread exiting
[1] [NTC] [STR] stream_stop: Closing motion-stream listen socket & active motion-stream sockets
[1] [NTC] [STR] stream_stop: Closed motion-stream listen socket & active motion-stream sockets
*** Error in `motion': free(): invalid pointer: 0xb4602dd8 ***
```

I think the error occurs when motion is streaming in greyscale because of my setup but it starts to streaming correctly during several events after it crashes. Any idea what I'm doing wrong? Maybe, do I have to change streaming codec option? 

Thanks in advance,
Daniel

### PR DESCRIPTION
**Pull request by Mr-DaveDev**
Closes #226 
This pull request addresses two regression issues.  The first commit addresses different behaviour of libav versus ffmpeg that causes crashes on 14.04 distributions.  The second commit addresses establishing a reasonable default quality for the containers that use h264.  The existing code will use lossless compression which results in excessively large files.

### CODE REVIEW

File: ffmpeg.c [hunk 1]
```diff
@@ -368,33 +368,32 @@ struct ffmpeg *ffmpeg_open(const char *ffmpeg_video_codec, char *filename,
...
-
         char crf[4];
         snprintf(crf, 4, "%d",ffmpeg->vbr);
         av_dict_set(&opts, "crf", crf, 0);
         av_dict_set(&opts, "tune", "zerolatency", 0);
     } else {
-        if (ffmpeg->vbr) c->flags |= CODEC_FLAG_QSCALE;
-        c->global_quality=ffmpeg->vbr;
+        /* The selection of 8000 in the else is a subjective number based upon viewing output files */
+        /* Default to 75% */
```
Comment (Mr-Dave) [inline ffmpeg.c]: And rightfully so!....On the first cut of the code, I put a default in there for the situation when the vbr was zero.  I removed the else condition when I observed that the constant bit rate applies in that situation.

**Comment by jogu** [comment]
seems ok to me then I think
