### PR TITLE
Multiple Issues

### LINKED ISSUE #134: Omit Masked areas in saved files
When saving pictures and videos, allow for the mask to be imposed.  This facilitates the meeting of various privacy requirements.  http://www.lavrsen.dk/foswiki/bin/view/Motion/FeatureRequest2016x03x07x060126

### LINKED ISSUE #219: motion loopback support for V4L2
Has anyone got loopback working with only V4L2 ?
The code currently does not compile the initialisation of the _motion_video_pipe_ or _video_pipe_ devices unless:
`#if defined(HAVE_LINUX_VIDEODEV_H) && !defined(WITHOUT_V4L) && !defined(BSD)`

On Debian jessie I have only `HAVE_LINUX_VIDEODEV2_H` defined.
thanks,
-dave

### LINKED ISSUE #221: Inconsistent framerate in beginning of motion-triggered videos (mp4/h264 encoded)
I have noticed some interesting behaviour of videos recorded by motion and encoded with mp4/h264 (though this may be an issue with more encoder types).

It essentially looks like the beginning few frames of a video are very sped-up compared to the rest.

I am guessing here (I don't know where to verify in the code itself), but it seems that `pre_capture` frames might be encoded at the `framerate` specified in the config, even though the camera itself may not be providing frames at that framerate; take, for example, a dark environment where frames take longer for a camera to retrieve: the effective framerate of the camera may only be 10 at that moment in time, but the pre_capture frames seem to be written at 24 as specified in the configuration. I have example videos and my (simplified) configuration is below.

```
event_gap 60
ffmpeg_output_movies on
ffmpeg_variable_bitrate 328
ffmpeg_video_codec mp4
framerate 24
height 800
lightswitch 60
locate_motion_mode on
locate_motion_style redbox
max_movie_time 0
minimum_motion_frames 1
post_capture 100
pre_capture 12
quality 85
stream_maxrate 24
stream_motion on
stream_port 8081
stream_quality 85
threshold 6000
videodevice /dev/v4l/by-id/usb-Microsoft_Microsoft®_LifeCam_Cinema_TM_-video-index0
width 1280
```

### LINKED ISSUE #263: Support for Greyscale format images?
I'm using a thermal imaging camera that outputs frames in the V4L2_PIX_FMT_GREY format. Is it possible to add support for this format in motion?

### LINKED ISSUE #264: segv in netcam_rtsp.c:893
When compiling this line ( netcam_rtsp.c:893 ) gets a GCC warning that the if() test is always TRUE because it compares two identical values. On execution, after failing to connect to a RTSP camera due to a problem with authentication, it SEGVs
```
Thread 2 "ml1" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6da4700 (LWP 29631)]
netcam_setup_rtsp (netcam=netcam@entry=0x7ffff0000960, url=url@entry=0x7ffff6da2c50) at netcam_rtsp.c:893
893	    if (url->port == url->port) netcam->rtsp->status = RTSP_NOTCONNECTED;
```
because netcam->rtsp is NULL
I think the test was supposed to be just (url->port) or (url->port != NULL)

### LINKED ISSUE #272: Complete transition to v4l2
v4l support was dropped from the kernel in 2011.  The project should eliminate the historic v4l support and upgrade all the components to v4l2.   The only "known" component at this time reliant upon v4l is the loopback functionality referenced in #219 .

### PR DESCRIPTION
**Pull request by Mr-DaveDev**
This is a fairly large pull request which was a work in progress for a while.  Anyone reviewing this PR is suggested to review it one commit at a time.  This pull:  

Closes #134 , Closes #219 , Closes #221 , Closes #263 , Closes #264 , Closes #272

Additional issues addressed include:
1.  Break apart the motion loop into functions so that they can be more easily reviewed, enhanced and maintained.  The implementation is in numerous commits for review purposes.  

2.  Consolidate the HAVE_FFMPEG scattered through the code to only have the preprocessor tests at a single destination.  

3.  Resolve a issue raised on the mailing list regarding the movies pausing to reflect the actual time between motion frames during an event.  

For items 1 and 2, these are first cuts to establish a basis for further enhancements later.

### CODE REVIEW

**Comment by tosiara** [comment]
Impressing changes
Regarding motion loop optimization. Do we plan also to implement plugin architecture? 10 years ago there were such plans for motion 4: http://www.lavrsen.dk/foswiki/bin/view/Motion/MotionPluginAPI

**Comment by Mr-Dave** [comment]
No we are not going for a plug-in structure.  This is to get the code into manageable functions.  The original motion loop function was over 1100 lines which was extremely difficult to navigate, enhance or debug.

File: vloopback_motion2.c [hunk 1]
```diff
@@ -0,0 +1,225 @@
+/*
+ *    vloopback_motion.c
```
Comment (slokhorst) [inline vloopback_motion2.c]: filename has changed (also in the `.h`)

File: CMakeLists.txt [hunk 2]
```diff
@@ -24,23 +24,20 @@ option(WITH_MMAL "enable MMAL (Multi-Media Abstraction Layer API) support for Ra
...
 check_include_files("linux/videodev2.h" HAVE_LINUX_VIDEODEV2_H)
-check_include_files("sys/videoio.h" HAVE_SYS_VIDEOIO_H)
-if(${WITH_V4L})
-	set(WITHOUT_V4L OFF)
-else(${WITH_V4L})
-	set(WITHOUT_V4L ON)
-endif(${WITH_V4L})
-set(MOTION_V4L2 ${HAVE_LINUX_VIDEODEV2_H})
+if(${WITH_V4L2})
+	set(WITHOUT_V4L2 HAVE_LINUX_VIDEODEV2_H)
```
Comment (slokhorst) [inline CMakeLists.txt]: Needs to be `set(WITHOUT_V4L2 NOT(HAVE_LINUX_VIDEODEV2_H))`

**Comment by Mr-Dave** [comment]
Thanks, I'll push those changes, the cmake system was a best effort without testing since it still doesn't work for me.

**Comment by jogu** [comment]
> the cmake system was a best effort without testing since it still doesn't work for me.

I think I'd forgotten and/or missed that - can you remind us how cmake fails please?

(I'm pretty busy for the next few days but will try to have a look through this code. Very grateful to @slokhorst for his review of it, I'm sure I wouldn't have spotted those points!)

**Comment by slokhorst** [comment]
I still haven't found a good solution for the workflow of @Mr-Dave at the bottom of #229. I think everything else should be working though. Please let me know if there are more issues.

**Comment by Mr-Dave** [comment]
@slokhorst The IF statement does look better but as I was making these same changes, it became clear that this will disable webcams for any non linux system since they will not have the header.    This pull isn't mergeable yet, I need to think about this.   i.e. Whether to add more tests in the configure or revise the source in video_freebsd.....

File: CMakeLists.txt [hunk 3]
```diff
@@ -92,6 +114,23 @@ if(WITH_MMAL)
 	list(APPEND SRC_FILES mmalcam.c)
 endif(WITH_MMAL)
 
+message("-- Configuration: " )
```
Comment (slokhorst) [inline CMakeLists.txt]: This shouldn't be needed, they are not interesting for every run and you can list them with `cmake . -LA` for debugging.

File: CMakeLists.txt [hunk 4]
```diff
@@ -32,12 +36,30 @@ set(HAVE_MMAL ${WITH_MMAL})
...
 set(HAVE_SQLITE3 ${WITH_SQLITE3})
-check_include_files("linux/videodev2.h" HAVE_LINUX_VIDEODEV2_H)
-if(${WITH_V4L2})
-	set(WITHOUT_V4L2 HAVE_LINUX_VIDEODEV2_H)
-else(${WITH_V4L2})
-	set(WITHOUT_V4L2 OFF)
-endif(${WITH_V4L2})
+
+set(WITHOUT_V4L2 ON)
+  if(CMAKE_SYSTEM_NAME MATCHES "FreeBSD" AND NOT(WITH_PWCBSD))
```
Comment (jogu) [inline CMakeLists.txt]: I don't think this 'if' needs to be intended?

The prevailing indentation in this file seems to be tabs, so I think it might be preferable to maintain that style (or switch completely to a different style).

File: ffmpeg.c [hunk 5]
```diff
@@ -321,109 +289,399 @@ static AVOutputFormat *get_oformat(const char *codec, char *filename){
...
+        retcd = timelapse_append(ffmpeg, pkt);
+    } else if (ffmpeg->tlapse == TIMELAPSE_NEW) {
+        retcd = av_write_frame(ffmpeg->oc, &pkt);
+    } else {
+        pts_interval = ((1000000L * (tv1->tv_sec - ffmpeg->start_time.tv_sec)) + tv1->tv_usec - ffmpeg->start_time.tv_usec) + 10000;
 
-    /* Allocation the output media context. */
-    ffmpeg->oc = avformat_alloc_context();
+//        MOTION_LOG(ERR, TYPE_ENCODER, NO_ERRNO, "%s: interval:%d img_sec:%d img_usec:%d strt_sec:%d strt_usec:%d "
+//                   ,pts_interval,tv1->tv_sec,tv1->tv_usec,ffmpeg->start_time.tv_sec,ffmpeg->start_time.tv_usec);
```
Comment (jogu) [inline ffmpeg.c]: Did you mean to include these lines? (Possibly they should be debug level and not commented out?)

File: ffmpeg.c [hunk 6]
```diff
@@ -321,109 +289,399 @@ static AVOutputFormat *get_oformat(const char *codec, char *filename){
...
+            ffmpeg->start_time.tv_usec = tv1->tv_usec ;
+            pts_interval = 1;
+        }
+        pkt.pts = av_rescale_q(pts_interval,(AVRational){1, 1000000L},ffmpeg->video_st->time_base);
+        if (pkt.pts <= ffmpeg->last_pts) pkt.pts = ffmpeg->last_pts + 1;
+        pkt.dts = pkt.pts;
+        retcd = av_write_frame(ffmpeg->oc, &pkt);
+        ffmpeg->last_pts = pkt.pts;
     }
+    //        MOTION_LOG(ERR, TYPE_ENCODER, NO_ERRNO, "%s: pts:%d dts:%d stream:%d interval %d",pkt.pts,pkt.dts,ffmpeg->video_st->time_base.den,pts_interval);
```
Comment (jogu) [inline ffmpeg.c]: Ditto.

File: conf.c [hunk 7]
```diff
@@ -293,6 +293,10 @@ config_param config_params[] = {
     "# V4L2_PIX_FMT_YUYV    : 15 'YUYV'\n"
     "# V4L2_PIX_FMT_YUV422P : 16 '422P'\n"
     "# V4L2_PIX_FMT_YUV420  : 17 'YU12'\n"
+    "# V4L2_PIX_FMT_YUV420  : 17 'YU12'\n"
```
Comment (Mr-Dave) [inline conf.c]: Yes that was duplicated. I'll push a change

File: motion.c [hunk 8]
```diff
@@ -894,13 +894,13 @@ static int motion_init(struct context *cnt)
...
 
-#if defined(HAVE_LINUX_VIDEODEV_H) && !defined(WITHOUT_V4L) && !defined(__FreeBSD__)
+#if !defined(WITHOUT_V4L2) && !defined(__FreeBSD__)
     /* open video loopback devices if enabled */
     if (cnt->conf.vidpipe) {
         MOTION_LOG(NTC, TYPE_ALL, NO_ERRNO, "%s: Opening video loopback device for normal pictures");
 
         /* vid_startpipe should get the output dimensions */
-        cnt->pipe = vid_startpipe(cnt->conf.vidpipe, cnt->imgs.width, cnt->imgs.height, cnt->imgs.type);
+        cnt->pipe = vid_startpipe(cnt->conf.vidpipe, cnt->imgs.width, cnt->imgs.height, V4L2_PIX_FMT_YUV420);
```
Comment (Mr-Dave) [inline motion.c]: Yes that is intentional.  In the old V4L days, it looks like Motion processed images in the format in which they were provided by the device.  The new V4L2 and Netcam way is that we always turn all our images into YUV420 then do the detection, overlays, processing, etc.  This is specifying to our loopback device that we will be sending images as YUV420 regardless of whether source image was RGB, Y11, YUYV, etc.  Ideally, this really just needs to get removed as a parameter.

File: ffmpeg.c (hunk 5 above)
Comment (Mr-Dave) [inline ffmpeg.c]: Yes, these were for my debugging but I didn't want to slow down this section by leaving it in as a call to the logger.  It would also flood the log since it writes for every frame.

**Comment by Mr-Dave** [comment]
Thanks for the review.  I agree entirely on revising the Without_V4L2 and was thinking it would in a different future pull where we also consolidate them into the called functions rather than around the calling.  (Similar to the HAVE_FFMPEG consolidation commits)

**Comment by jogu** [comment]
Sounds good.

For WITH_V4L2 ifdef consolidation, it might be worth considering adding a proper API for cameras instead - something along the lines of https://github.com/jogu/motion/commit/83c4867108e5fd15ae84fd6edadb75ec8560635d (unfortunately that commit has a load of other stuff in it that makes the fairly simple change to start adding a generic camera API hard to spot - it basically has a struct with function pointers, which a camera fills in with pointers to it's init/cleanup/get next image functions, meaning all the "if it's a netcam, call the netcam get next image function... if it's a v4l device, call..." type logic can be removed from the core of motion).
